/**
 * lib/categories.ts
 * Centralized arXiv category mappings (source: https://arxiv.org/category_taxonomy)
 */

export const CATEGORY_LABELS: Record<string, string> = {
  // Computer Science
  'cs.AI': 'Artificial Intelligence',
  'cs.AR': 'Hardware Architecture',
  'cs.CC': 'Computational Complexity',
  'cs.CE': 'Computational Engineering',
  'cs.CG': 'Computational Geometry',
  'cs.CL': 'Computation and Language',
  'cs.CR': 'Cryptography and Security',
  'cs.CV': 'Computer Vision',
  'cs.CY': 'Computers and Society',
  'cs.DB': 'Databases',
  'cs.DC': 'Distributed Computing',
  'cs.DL': 'Digital Libraries',
  'cs.DM': 'Discrete Mathematics',
  'cs.DS': 'Data Structures and Algorithms',
  'cs.ET': 'Emerging Technologies',
  'cs.FL': 'Formal Languages',
  'cs.GL': 'General Literature',
  'cs.GR': 'Graphics',
  'cs.GT': 'Computer Science and Game Theory',
  'cs.HC': 'Human-Computer Interaction',
  'cs.IR': 'Information Retrieval',
  'cs.IT': 'Information Theory',
  'cs.LG': 'Machine Learning',
  'cs.LO': 'Logic in Computer Science',
  'cs.MA': 'Multiagent Systems',
  'cs.MM': 'Multimedia',
  'cs.MS': 'Mathematical Software',
  'cs.NA': 'Numerical Analysis',
  'cs.NE': 'Neural and Evolutionary Computing',
  'cs.NI': 'Networking and Internet Architecture',
  'cs.OH': 'Other Computer Science',
  'cs.OS': 'Operating Systems',
  'cs.PF': 'Performance',
  'cs.PL': 'Programming Languages',
  'cs.RO': 'Robotics',
  'cs.SC': 'Symbolic Computation',
  'cs.SD': 'Sound',
  'cs.SE': 'Software Engineering',
  'cs.SI': 'Social and Information Networks',
  'cs.SY': 'Systems and Control',

  // Mathematics
  'math.AC': 'Commutative Algebra',
  'math.AG': 'Algebraic Geometry',
  'math.AP': 'Analysis of PDEs',
  'math.AT': 'Algebraic Topology',
  'math.CA': 'Classical Analysis and ODEs',
  'math.CO': 'Combinatorics',
  'math.CT': 'Category Theory',
  'math.CV': 'Complex Variables',
  'math.DG': 'Differential Geometry',
  'math.DS': 'Dynamical Systems',
  'math.FA': 'Functional Analysis',
  'math.GM': 'General Mathematics',
  'math.GN': 'General Topology',
  'math.GR': 'Group Theory',
  'math.GT': 'Geometric Topology',
  'math.HO': 'History and Overview',
  'math.IT': 'Information Theory',
  'math.KT': 'K-Theory and Homology',
  'math.LO': 'Logic',
  'math.MG': 'Metric Geometry',
  'math.MP': 'Mathematical Physics',
  'math.NA': 'Numerical Analysis',
  'math.NT': 'Number Theory',
  'math.OA': 'Operator Algebras',
  'math.OC': 'Optimization and Control',
  'math.PR': 'Probability',
  'math.QA': 'Quantum Algebra',
  'math.RA': 'Rings and Algebras',
  'math.RT': 'Representation Theory',
  'math.SG': 'Symplectic Geometry',
  'math.SP': 'Spectral Theory',
  'math.ST': 'Statistics Theory',

  // Statistics
  'stat.AP': 'Statistics - Applications',
  'stat.CO': 'Statistics - Computation',
  'stat.ME': 'Statistics - Methodology',
  'stat.ML': 'Statistics - Machine Learning',
  'stat.OT': 'Statistics - Other',
  'stat.TH': 'Statistics - Theory',

  // Physics - Astrophysics
  'astro-ph.CO': 'Cosmology and Nongalactic Astrophysics',
  'astro-ph.EP': 'Earth and Planetary Astrophysics',
  'astro-ph.GA': 'Astrophysics of Galaxies',
  'astro-ph.HE': 'High Energy Astrophysical Phenomena',
  'astro-ph.IM': 'Instrumentation and Methods for Astrophysics',
  'astro-ph.SR': 'Solar and Stellar Astrophysics',

  // Physics - Condensed Matter
  'cond-mat.dis-nn': 'Disordered Systems and Neural Networks',
  'cond-mat.mes-hall': 'Mesoscale and Nanoscale Physics',
  'cond-mat.mtrl-sci': 'Materials Science',
  'cond-mat.other': 'Other Condensed Matter',
  'cond-mat.quant-gas': 'Quantum Gases',
  'cond-mat.soft': 'Soft Condensed Matter',
  'cond-mat.stat-mech': 'Statistical Mechanics',
  'cond-mat.str-el': 'Strongly Correlated Electrons',
  'cond-mat.supr-con': 'Superconductivity',

  // Physics - Other
  'gr-qc': 'General Relativity and Quantum Cosmology',
  'hep-ex': 'High Energy Physics - Experiment',
  'hep-lat': 'High Energy Physics - Lattice',
  'hep-ph': 'High Energy Physics - Phenomenology',
  'hep-th': 'High Energy Physics - Theory',
  'math-ph': 'Mathematical Physics',
  'nucl-ex': 'Nuclear Experiment',
  'nucl-th': 'Nuclear Theory',
  'quant-ph': 'Quantum Physics',

  // Electrical Engineering
  'eess.AS': 'Audio and Speech Processing',
  'eess.IV': 'Image and Video Processing',
  'eess.SP': 'Signal Processing',
  'eess.SY': 'Systems and Control',

  // Economics
  'econ.EM': 'Econometrics',
  'econ.GN': 'General Economics',
  'econ.TH': 'Theoretical Economics',

  // Quantitative Biology
  'q-bio.BM': 'Biomolecules',
  'q-bio.CB': 'Cell Behavior',
  'q-bio.GN': 'Genomics',
  'q-bio.MN': 'Molecular Networks',
  'q-bio.NC': 'Neurons and Cognition',
  'q-bio.OT': 'Other Quantitative Biology',
  'q-bio.PE': 'Populations and Evolution',
  'q-bio.QM': 'Quantitative Methods',
  'q-bio.SC': 'Subcellular Processes',
  'q-bio.TO': 'Tissues and Organs',

  // Quantitative Finance
  'q-fin.CP': 'Computational Finance',
  'q-fin.EC': 'Economics',
  'q-fin.GN': 'General Finance',
  'q-fin.MF': 'Mathematical Finance',
  'q-fin.PM': 'Portfolio Management',
  'q-fin.PR': 'Pricing of Securities',
  'q-fin.RM': 'Risk Management',
  'q-fin.ST': 'Statistical Finance',
  'q-fin.TR': 'Trading and Market Microstructure',
};

// Short labels for compact UI (e.g., author stats chips)
export const CATEGORY_SHORT_LABELS: Record<string, string> = {
  'cs.AI': 'AI',
  'cs.AR': 'Architecture',
  'cs.CC': 'Complexity',
  'cs.CE': 'Comp. Eng.',
  'cs.CG': 'Comp. Geom.',
  'cs.CL': 'NLP',
  'cs.CR': 'Crypto',
  'cs.CV': 'Vision',
  'cs.CY': 'Society',
  'cs.DB': 'Databases',
  'cs.DC': 'Distributed',
  'cs.DL': 'Digital Libs',
  'cs.DM': 'Discrete Math',
  'cs.DS': 'Algorithms',
  'cs.ET': 'Emerging Tech',
  'cs.FL': 'Formal Lang.',
  'cs.GL': 'General Lit.',
  'cs.GR': 'Graphics',
  'cs.GT': 'Game Theory',
  'cs.HC': 'HCI',
  'cs.IR': 'Info Retrieval',
  'cs.IT': 'Info Theory',
  'cs.LG': 'ML',
  'cs.LO': 'Logic',
  'cs.MA': 'Multiagent',
  'cs.MM': 'Multimedia',
  'cs.MS': 'Math Software',
  'cs.NA': 'Numerical',
  'cs.NE': 'Neural Computing',
  'cs.NI': 'Networking',
  'cs.OH': 'Other CS',
  'cs.OS': 'OS',
  'cs.PF': 'Performance',
  'cs.PL': 'Prog. Lang.',
  'cs.RO': 'Robotics',
  'cs.SC': 'Symbolic',
  'cs.SD': 'Sound',
  'cs.SE': 'Software Eng.',
  'cs.SI': 'Social Networks',
  'cs.SY': 'Systems',
  'math.ST': 'Stats Theory',
  'stat.ME': 'Stats Method.',
  'stat.ML': 'Stats ML',
  'stat.AP': 'Stats Apps',
  'stat.CO': 'Stats Comp.',
  'stat.TH': 'Stats Theory',
};

export function getCategoryLabel(code: string): string {
  return CATEGORY_LABELS[code] ?? code;
}

export function getCategoryShortLabel(code: string): string {
  return CATEGORY_SHORT_LABELS[code] ?? CATEGORY_LABELS[code] ?? code;
}
