import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '../components/Navbar';
import { Card } from '../components/Card';
import { ChevronDown } from 'lucide-react';

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about ArxivCSExplorer — how it works, what AI models are used, and more.',
};

const FAQS = [
  {
    q: 'What is ArxivCSExplorer?',
    a: 'ArxivCSExplorer is a fast, AI-powered search engine for Computer Science arXiv papers. It indexes recent papers from ML, NLP, computer vision, cryptography, systems, algorithms, and more — and generates concise AI summaries so you can understand a paper in 60 seconds without reading the full PDF.',
  },
  {
    q: 'Where does the paper data come from?',
    a: 'Papers are fetched directly from the official arXiv API (export.arxiv.org) and are scoped strictly to CS categories: cs.AI, cs.LG, cs.CL, cs.CV, cs.CR, cs.DC, cs.DS, and more.',
  },
  {
    q: 'What AI model generates the summaries?',
    a: 'Summaries are generated by Llama 3.1 8B Instruct running on Cloudflare Workers AI. A single structured JSON prompt consolidates all summary fields (TL;DR, contributions, methods, limitations, beginner and technical explanations) into one inference call per paper.',
  },
  {
    q: 'Are the AI summaries accurate?',
    a: 'They are generally reliable for well-structured abstracts, but AI summaries can occasionally miss nuance or misrepresent results. Always read the original abstract — or the full paper — for anything you intend to cite or build on.',
  },
  {
    q: 'How does the search work?',
    a: 'Search uses a hybrid approach: full-text BM25 keyword search (with title boosted 10× over abstract) combined with semantic vector search via Cloudflare Vectorize. Results from both paths are merged and ranked using a 25% keyword / 75% semantic weighting, which works well for research paper retrieval.',
  },
  {
    q: 'How are related papers computed?',
    a: 'When a paper is ingested, we query Vectorize for the 8 most similar papers by embedding cosine similarity. These are stored in our database and served directly — Vectorize is never queried during a user request, which keeps the related papers sidebar fast.',
  },
  {
    q: 'Is there a rate limit?',
    a: 'There is no login or per-user rate limit for browsing and searching. The ingestion pipeline runs at a conservative rate (10 papers/hour) to stay within free-tier AI budgets.',
  },
  {
    q: 'How do I look up a specific paper?',
    a: 'Paste the arXiv ID (e.g. 2312.00752) or the full arXiv URL into the search box. You\'ll be taken directly to the paper detail page.',
  },
  {
    q: 'Can I access the source code?',
    a: 'Yes — the project is open source. Find it on GitHub via the link in the footer.',
  },
  {
    q: 'Who built this?',
    a: 'ArxivCSExplorer was built by Teycir Ben Soltane as a fast, cache-first CS paper explorer.',
  },
];

export default function FaqPage() {
  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto w-full px-4 py-10 flex-1">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs font-mono text-neon-red/30 mb-6">
          <Link href="/" className="hover:text-neon-red/60 transition-colors">Home</Link>
          <span>/</span>
          <span className="text-neon-red/50">FAQ</span>
        </nav>

        <h1 className="text-2xl font-mono font-bold text-white/90 mb-1">FAQ</h1>
        <p className="text-sm text-neon-red/40 font-mono mb-10">
          Frequently asked questions about ArxivCSExplorer.
        </p>

        <div className="flex flex-col gap-4">
          {FAQS.map(({ q, a }, i) => (
            <Card key={i}>
              <div className="flex items-start gap-3">
                <ChevronDown size={14} className="text-neon-red/40 flex-shrink-0 mt-0.5" />
                <div>
                  <h2 className="text-sm font-mono font-semibold text-white/85 mb-2">{q}</h2>
                  <p className="text-xs text-white/55 leading-relaxed">{a}</p>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </main>
    </>
  );
}
