import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '../components/Navbar';
import { Card } from '../components/Card';
import { ChevronDown } from 'lucide-react';

export const metadata: Metadata = {
  title: 'FAQ',
  description: 'Frequently asked questions about ArxivCSExplorer — how it works, what AI models are used, and more.',
};

const FAQS = [
  {
    q: 'What is ArxivCSExplorer?',
    a: 'ArxivCSExplorer is a fast, AI-powered search engine for arXiv papers. It provides semantic search, pre-generated AI summaries, citation tracking, bookmarks with collections, paper comparison, claim classification, achievements, and personalized recommendations — all without requiring login.',
  },
  {
    q: 'Where does the paper data come from?',
    a: 'Papers are fetched directly from the official arXiv API (export.arxiv.org). Additional metadata comes from Semantic Scholar (citations), CrossRef (journal info), OpenAlex (concepts, affiliations), and Papers With Code (repositories, benchmarks).',
  },
  {
    q: 'What AI models power the summaries?',
    a: 'Summaries are generated by Llama 3.1 8B Instruct via Cloudflare Workers AI for live inference, or locally via Ollama (Gemma 4 8B) for bulk ingestion. Embeddings use BGE-base-en-v1.5 (Workers AI) or nomic-embed-text (Ollama). A single structured JSON prompt generates TL;DR, contributions, methods, limitations, beginner/technical explanations, keywords, paper type, prerequisites, and follow-up questions.',
  },
  {
    q: 'Are the AI summaries accurate?',
    a: 'They are generally reliable for well-structured abstracts, but AI summaries can occasionally miss nuance or misrepresent results. Always read the original abstract — or the full paper — for anything you intend to cite or build on.',
  },
  {
    q: 'How does the hybrid search work?',
    a: 'Search combines SQLite FTS5 keyword search (title boosted 10:1:5 over abstract and authors) with Cloudflare Vectorize semantic search. Results are merged with 25% keyword / 75% semantic weighting, deduplicated, and cached in KV with 2h TTL.',
  },
  {
    q: 'What search filters are available?',
    a: 'You can filter by author (substring match), minimum citation count, arXiv category (cs.LG, cs.CL, etc.), and date range (day/week/month). All filters work together and with hybrid search. Each filter combination gets its own KV cache key.',
  },
  {
    q: 'How do bookmarks and collections work?',
    a: 'Bookmarks are stored client-side in localStorage with 90-day TTL. You can create named collections, assign bookmarks to collections, add notes, track reading status (unread/reading/done), and export as JSON or BibTeX. There\'s a soft cap of 100 bookmarks with automatic pruning of oldest entries. No login required.',
  },
  {
    q: 'Where do citation counts come from?',
    a: 'Citation counts are fetched from Semantic Scholar API via hourly cron. Historical citation data is stored in citation_snapshots table. Both citation count and influential citation count are tracked.',
  },
  {
    q: 'How are related papers computed?',
    a: 'When a paper is ingested, we query Vectorize for the top-8 semantically similar papers by embedding cosine similarity. These are pre-computed and stored in the related_papers table, so related papers load instantly without querying Vectorize during user requests.',
  },
  {
    q: 'Can I compare multiple papers side-by-side?',
    a: 'Yes — use the /compare route with up to 6 paper IDs (e.g., /compare?ids=2301.07041,2302.13971). The comparison view shows TL;DR, key contributions, methods, limitations, and technical summaries in a responsive grid layout.',
  },
  {
    q: 'What is claim classification?',
    a: 'Claim classification uses AI to analyze whether a scientific claim is supported, contradicted, or neutral based on a paper\'s content. It\'s powered by Llama 3.1 and helps verify research statements.',
  },
  {
    q: 'Is there an RSS feed?',
    a: 'Yes — subscribe to /rss.xml for trending papers from the last week with TL;DR summaries. The feed is cached for 1 hour and updates as new papers are ingested.',
  },
  {
    q: 'What are achievements?',
    a: 'Achievements are gamified badges (bronze/silver/gold tiers) for paper exploration milestones: first bookmark, reading 10 papers, visiting 5 topics, comparing papers, building reading streaks, etc. All stored client-side in localStorage without requiring login.',
  },
  {
    q: 'Is there a rate limit?',
    a: 'No login or API key is required. Standard per-IP rate limiting applies (100 requests/minute with a 2-minute lockout on excess) to protect the service. In practice this limit is never hit during normal browsing. The ingestion pipeline processes 1 paper per minute (113 papers/day max) to stay within free-tier AI budgets.',
  },
  {
    q: 'How do I look up a specific paper?',
    a: 'Paste the arXiv ID (e.g. 2312.00752) or the full arXiv URL into the search box. You\'ll be taken directly to the paper detail page with AI summary, related papers, and citation data.',
  },
  {
    q: 'Can AI assistants use this?',
    a: 'Yes — install the arxiv-cli tool for programmatic access (search, trending, topics, authors). The CLI is designed for AI assistants like Claude and ChatGPT. There are also /ai.txt and /llms.txt routes for agent discovery.',
  },
  {
    q: 'What is the tech stack?',
    a: 'Next.js 16 deployed as Cloudflare Worker (OpenNext), API on Cloudflare Workers, D1 (SQLite) database, Vectorize for embeddings, KV for caching, Workers AI for inference. Global edge deployment with ISR rendering (10min revalidation).',
  },
  {
    q: 'Can I access the source code?',
    a: 'Yes — the project is open source under BSL 1.1 (free for non-commercial use, converts to MIT on 2029-06-01). Find it on GitHub via the link in the footer.',
  },
  {
    q: 'Who built this?',
    a: 'ArxivCSExplorer was built by Teycir Ben Soltane as a fast, semantic-first research paper explorer with zero-login access to all features.',
  },
];

export default function FaqPage() {
  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto w-full px-4 py-10 flex-1">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs font-mono text-neon-red/30 mb-6">
          <Link href="/" className="hover:text-neon-red/60 transition-colors">Home</Link>
          <span>/</span>
          <span className="text-neon-red/50">FAQ</span>
        </nav>

        <h1 className="text-2xl font-mono font-bold text-white/90 mb-1">FAQ</h1>
        <p className="text-sm text-neon-red/40 font-mono mb-10">
          Frequently asked questions about ArxivCSExplorer.
        </p>

        <div className="flex flex-col gap-4">
          {FAQS.map(({ q, a }, i) => (
            <Card key={i}>
              <div className="flex items-start gap-3">
                <ChevronDown size={14} className="text-neon-red/40 flex-shrink-0 mt-0.5" />
                <div>
                  <h2 className="text-sm font-mono font-semibold text-white/85 mb-2">{q}</h2>
                  <p className="text-xs text-white/55 leading-relaxed">{a}</p>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </main>
    </>
  );
}
